### PR TITLE
[EAHW 2047] - Setup hash routing

### PR DESCRIPTION
**Pull request by sewerynmi**

### CODE REVIEW

**Comment by sewerynmi** [comment]
Here is the article with the solution https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

**Review by LaurieBennett — COMMENTED** [review]
Code looks good, just need to add the extra line needed in the .env file to the README.md

**Comment by holly-blues** [comment]
Just for my understanding, what was the problem that needed resolving with those Keycloak changes? Was is related to the Hash Routing change, or something else?

**Comment by sewerynmi** [comment]
@holly-blues With each page reload, the Keycloak was adding 'state' param to the  URL and the APP does not have a Route for that sort of URL. This caused React to not load any component. My solution still have Keycloak 'check user login' functionality, but is happening behind the scenes without using URL's.

**Comment by holly-blues** [comment]
@sewerynmi ok, got it - thanks.

**Review by holly-blues — APPROVED** [review]

**Review by LaurieBennett — APPROVED** [review]

**Pull request merged**
